### ISSUE TITLE
Device list was not loading.

### ISSUE THREAD

**Issue by zalewskigrzegorz** [otaviojr/node-red-contrib-smartthings#15]
Hello after app configuration I cannot add any devices
![obraz](https://user-images.githubusercontent.com/12560152/71921097-70712d00-3188-11ea-808e-08248c7d575f.png)
In simulator looks like everything should work:
![obraz](https://user-images.githubusercontent.com/12560152/71921366-01480880-3189-11ea-8df7-e20b8d02545b.png)

**Comment by u076894** [comment]
It's not clear to me how this was resolved. I currently have the same issue. I'm at the latest release. SmartThings IDE tests without error, but I cannot retrieve device list when attempting to deploy a test in node-red. I generated a token, as instructed, and pasted it in properties window. I presume the other fields can be arbitrary, as mentioned by Otavio as token field is only 'relevant' field. I must be missing something simple. Suggestions? Russ

**Comment by otaviojr** [comment]
Just deploy your flow. Event without selecting a device. Then edit the node and the list will load.

I'm working on this. But for now that should solve your problem.

regards.

**Comment by otaviojr** [comment]
If you wan't to try. I've deployed a new version. 0.0.19. That will solve this issue.

**Comment by JasonKChow** [comment]
This is still a problem. Oddly, trying versions .18, .19, and .20 none of them work anymore.

**Comment by jawgardner** [comment]
> This is still a problem. Oddly, trying versions .18, .19, and .20 none of them work anymore. Seems to be related to some rate-limiting thing.

I am also having this issue. My nodered is running in a docker container, on a host network. I can see in the terminal of that container that api.smartthings.com/v1/devices is being called successfully. However, nothing is being returned in the devices array for some reason.

I get the same output in ide simulator as OP.

I suspect something to do with the SmartApp configuration, or maybe Samsung changed something in their api? 

Does anyone have any thoughts? I'd be happy to debug if anyone has any ideas. 

Thank you all for your work on making this plugin work.

**Comment by qwiksilver** [comment]
> > This is still a problem. Oddly, trying versions .18, .19, and .20 none of them work anymore. Seems to be related to some rate-limiting thing.
> 
> I am also having this issue. My nodered is running in a docker container, on a host network. I can see in the terminal of that container that api.smartthings.com/v1/devices is being called successfully. However, nothing is being returned in the devices array for some reason.
> 
> I get the same output in ide simulator as OP.
> 
> I suspect something to do with the SmartApp configuration, or maybe Samsung changed something in their api?
> 
> Does anyone have any thoughts? I'd be happy to debug if anyone has any ideas.
> 
> Thank you all for your work on making this plugin work.

Same here. Devices will not populate. I have a local instance of Node Red on an rpi. I've tried many variation for the address. Currently, I am using http://192.x.x.x:1880/smartthings/webhook (x's are the address of the rpi node red instance).

Frank

**Comment by KOEPKEJR** [comment]
I just ran into this issue after a year or so of use.  I went to update a flow and the Device list will not populate.  Was anyone ever able to resolve this issue?
